runtime: php74 # Replace with php74 to use PHP 7.4

env_variables:
  DEPLOY_URL: "https://crafty-coral-281804.uc.r.appspot.com"

handlers:
  - url: /(.*\.(gif|png|jpg|css|js))$
    static_files: public/\1
    upload: public/.*\.(gif|png|jpg|css|js)$

  - url: /.*
    secure: always
    redirect_http_response_code: 301
    script: auto
